title: My Website
description: A website using Minimal Mistakes theme
url: "https://solaiarasi.github.io"
baseurl: "/minimal-mistake/"  # For project site, leave empty for personal site

#remote_theme: mmistakes/minimal-mistakes
#remote_theme: "mmistakes/minimal-mistakes@4.27.3"
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-include-cache

author:
  name: Your Name
